# Generated by Django 5.1.15 on 2026-07-04 22:49

from django.db import migrations, models


def accept_existing_follows(apps, schema_editor):
    """Any follow that already existed predates the request/approval feature —
    it was created under the old instant-follow behaviour, so it's a real
    accepted relationship. Flip those from the new 'pending' default to
    'accepted' so nobody loses a follow when this migration runs."""
    Follow = apps.get_model("api", "Follow")
    Follow.objects.update(status="accepted")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=8),
        ),
        # Backfill: existing rows were instant-follows → treat as accepted.
        # Reverse is a no-op (the column is dropped by reversing AddField).
        migrations.RunPython(accept_existing_follows, migrations.RunPython.noop),
    ]
