# Generated by Django 5.1.15 on 2026-07-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_follow_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
