# Generated by Django 5.1.15 on 2026-07-06 06:21

import api.imaging
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_connections_and_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=api.imaging.post_image_upload_to),
                ),
                (
                    "thumbnail",
                    models.ImageField(upload_to=api.imaging.post_thumb_upload_to),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.post",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
