# Generated by Django 6.0.7 on 2026-07-13 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.comment')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.connection')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.group')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='api_notific_recipie_5c719b_idx'), models.Index(fields=['recipient', 'seen_at'], name='api_notific_recipie_1cc3f4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('connection__isnull', True), ('group__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', True), ('group__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('connection__isnull', True), ('group__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', True), ('group__isnull', False), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', False), ('group__isnull', True), ('post__isnull', True)), _connector='OR'), name='notification_at_most_one_target')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='unique_user_notification_kind')],
            },
        ),
    ]
