# Generated by Django 6.0.7 on 2026-07-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_postcommentread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, db_index=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_url', models.URLField(blank=True)),
                ('location_note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], db_index=True, default='planning', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('declined', 'Declined')], max_length=8)),
                ('guests', models.SmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('date', 'Date'), ('time', 'Time'), ('location', 'Location'), ('custom', 'Custom')], max_length=8)),
                ('question', models.CharField(max_length=200)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=6)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('time_value', models.TimeField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=200)),
                ('order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_at_most_one_target',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation'), ('event_created', 'New group event'), ('poll_opened', 'Poll opened on an event'), ('event_scheduled', 'Event date set'), ('event_updated', 'Event changed'), ('event_cancelled', 'Event cancelled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation'), ('event_created', 'New group event'), ('poll_opened', 'Poll opened on an event'), ('event_scheduled', 'Event date set'), ('event_updated', 'Event changed'), ('event_cancelled', 'Event cancelled')], max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_organised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.event'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('connection__isnull', True), ('event__isnull', True), ('group__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', True), ('event__isnull', True), ('group__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('connection__isnull', True), ('event__isnull', True), ('group__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', True), ('event__isnull', True), ('group__isnull', False), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', False), ('event__isnull', True), ('group__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('connection__isnull', True), ('event__isnull', False), ('group__isnull', True), ('post__isnull', True)), _connector='OR'), name='notification_at_most_one_target'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='api.event'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='api.event'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.poll'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.polloption'),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['group', 'event_date'], name='api_event_group_i_668b80_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_rsvp'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('option', 'voter'), name='unique_poll_vote'),
        ),
    ]
