# Generated by Django 6.0.7 on 2026-07-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_eventrsvp_poll_polloption_pollvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='decided_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.polloption'),
        ),
    ]
