# Generated by Django 6.0.7 on 2026-07-20 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_devicepushtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push",
                        to="api.notification",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at", "created_at"],
                        name="api_pushout_sent_at_a75068_idx",
                    )
                ],
            },
        ),
    ]
