# Generated by Django 6.0.7 on 2026-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_pushoutbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushoutbox",
            name="delivered_tokens",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
