# Generated by Django 6.0.7 on 2026-07-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pushoutbox_delivered_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=200, unique=True)),
                ('expo_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='api_pushrec_created_e4acfa_idx')],
            },
        ),
    ]
