# Generated by Django 6.0.7 on 2026-07-26 07:30
#
# Phase 9b M0: a report can target a message, and carries a snapshot of its text.
# Purely additive — two nullable/defaulted columns and a *widened* check
# constraint (post XOR comment → exactly one of post/comment/message), so every
# existing report row still satisfies it and no data is rewritten.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_message_pushes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_targets_exactly_one',
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.message'),
        ),
        migrations.AddField(
            model_name='report',
            name='message_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('message__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('message__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('message__isnull', False), ('post__isnull', True)), _connector='OR'), name='report_targets_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter', 'message'), name='one_report_per_reporter_message'),
        ),
    ]
