# Generated by Django 6.0.7 on 2026-07-29 06:42

import api.imaging
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_message_reply_threads"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image")], default="image", max_length=16
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=api.imaging.message_attachment_upload_to
                    ),
                ),
                (
                    "thumbnail",
                    models.FileField(
                        upload_to=api.imaging.message_attachment_thumb_upload_to
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.message",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
