# Generated by Django 6.0.7 on 2026-07-29 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_message_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation'), ('event_created', 'New group event'), ('poll_opened', 'Poll opened on an event'), ('event_scheduled', 'Event date set'), ('event_updated', 'Event changed'), ('event_cancelled', 'Event cancelled'), ('mention', 'You were mentioned in a chat')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation'), ('event_created', 'New group event'), ('poll_opened', 'Poll opened on an event'), ('event_scheduled', 'Event date set'), ('event_updated', 'Event changed'), ('event_cancelled', 'Event cancelled'), ('mention', 'You were mentioned in a chat')], max_length=32),
        ),
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='api.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='api_message_message_2468d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user'), name='unique_message_mention')],
            },
        ),
    ]
