# Generated by Django 6.0.7 on 2026-08-04 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_comment_edit_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postcommentread',
            name='unique_post_comment_read',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='reaction_targets_exactly_one',
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.event'),
        ),
        migrations.AddField(
            model_name='postcommentread',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reads', to='api.event'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.event'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
        migrations.AlterField(
            model_name='postcommentread',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reads', to='api.post'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['event', 'created_at'], name='api_comment_event_i_1271c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('post__isnull', False)), models.Q(('event__isnull', False), ('post__isnull', True)), _connector='OR'), name='comment_targets_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='postcommentread',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'user'), name='unique_post_comment_read'),
        ),
        migrations.AddConstraint(
            model_name='postcommentread',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'user'), name='unique_event_comment_read'),
        ),
        migrations.AddConstraint(
            model_name='postcommentread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('post__isnull', False)), models.Q(('event__isnull', False), ('post__isnull', True)), _connector='OR'), name='comment_read_targets_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('event__isnull', True), ('message__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('event__isnull', True), ('message__isnull', True), ('post__isnull', True)), models.Q(('comment__isnull', True), ('event__isnull', True), ('message__isnull', False), ('post__isnull', True)), models.Q(('comment__isnull', True), ('event__isnull', False), ('message__isnull', True), ('post__isnull', True)), _connector='OR'), name='reaction_targets_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('user', 'event', 'emoji'), name='unique_user_event_emoji'),
        ),
    ]
