# Generated by Django 6.0.7 on 2026-08-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_event_comments_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation'), ('event_created', 'New group event'), ('poll_opened', 'Poll opened on an event'), ('event_scheduled', 'Event date set'), ('event_updated', 'Event changed'), ('event_cancelled', 'Event cancelled'), ('event_comment', 'Comment on your event'), ('mention', 'You were mentioned in a chat')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('post_reply', 'Reply to your post'), ('comment_reply', 'Reply to your comment'), ('reaction', 'Reaction to your content'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('group_invite', 'Group invitation'), ('event_created', 'New group event'), ('poll_opened', 'Poll opened on an event'), ('event_scheduled', 'Event date set'), ('event_updated', 'Event changed'), ('event_cancelled', 'Event cancelled'), ('event_comment', 'Comment on your event'), ('mention', 'You were mentioned in a chat')], max_length=32),
        ),
    ]
