# Generated by Django 6.0.7 on 2026-08-05 07:53

import api.imaging
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_event_comment_notification_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("post_reply", "Reply to your post"),
                    ("comment_reply", "Reply to your comment"),
                    ("reaction", "Reaction to your content"),
                    ("connection_request", "Connection request"),
                    ("connection_accepted", "Connection accepted"),
                    ("group_invite", "Group invitation"),
                    ("event_created", "New group event"),
                    ("poll_opened", "Poll opened on an event"),
                    ("event_scheduled", "Event date set"),
                    ("event_updated", "Event changed"),
                    ("event_cancelled", "Event cancelled"),
                    ("event_comment", "Comment on your event"),
                    ("event_photos", "Photos added to an event"),
                    ("mention", "You were mentioned in a chat"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="kind",
            field=models.CharField(
                choices=[
                    ("post_reply", "Reply to your post"),
                    ("comment_reply", "Reply to your comment"),
                    ("reaction", "Reaction to your content"),
                    ("connection_request", "Connection request"),
                    ("connection_accepted", "Connection accepted"),
                    ("group_invite", "Group invitation"),
                    ("event_created", "New group event"),
                    ("poll_opened", "Poll opened on an event"),
                    ("event_scheduled", "Event date set"),
                    ("event_updated", "Event changed"),
                    ("event_cancelled", "Event cancelled"),
                    ("event_comment", "Comment on your event"),
                    ("event_photos", "Photos added to an event"),
                    ("mention", "You were mentioned in a chat"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=api.imaging.event_photo_upload_to),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=api.imaging.event_photo_thumb_upload_to
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.event",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"],
                        name="api_eventph_event_i_b49a89_idx",
                    )
                ],
            },
        ),
    ]
