# Generated by Django 6.0.7 on 2026-08-13 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_event_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devicepushtoken",
            name="preview_token_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="devicepushtoken",
            name="show_previews",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="devicepushtoken",
            index=models.Index(
                fields=["preview_token_hash"], name="api_devicep_preview_a1d61a_idx"
            ),
        ),
    ]
