# Generated by Django 5.1.15 on 2026-07-06 06:21

import api.imaging
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.imaging.avatar_upload_to
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_thumb",
            field=models.ImageField(
                blank=True, null=True, upload_to=api.imaging.avatar_thumb_upload_to
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
