# Generated by Django 6.0.7 on 2026-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_avatar_user_avatar_thumb_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tos_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
