# Generated by Django 6.0.7 on 2026-07-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_read_receipts',
            field=models.BooleanField(default=True),
        ),
    ]
