"""
Django settings for config project.

Originally generated by 'django-admin startproject' (Django 5.1); the project
now runs Django 6.0 (bumped by Dependabot — pinned in pyproject.toml/uv.lock).

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    """Read a boolean-ish environment variable ("1"/"true"/"yes")."""
    return os.environ.get(name, str(default)).lower() in {"1", "true", "yes"}


def env_int(name, default):
    """Read an int-valued env var, falling back to ``default`` (with a warning)
    if it's set to something non-numeric.

    Deliberately does *not* raise: a typo in a non-critical tuning value (e.g.
    ``EMAIL_PORT``) should degrade to the default, not crash settings import and
    take the whole site down. Security-critical values (SECRET_KEY) still fail
    loudly on their own.
    """
    raw = os.environ.get(name)
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        warnings.warn(
            f"{name}={raw!r} is not a valid integer; using default {default}.",
            stacklevel=2,
        )
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Secure by default: DEBUG is off unless explicitly enabled. The dev
# docker-compose sets DJANGO_DEBUG=true, so local development is unaffected.
DEBUG = env_bool("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# In development we fall back to a throwaway key. With DEBUG off (i.e. anything
# that looks like production) the key MUST come from the environment — we refuse
# to boot with a repo-visible key, since a public SECRET_KEY lets anyone forge
# session cookies and signed tokens (password resets, etc.).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # Dev-only fallback; the `else` branch above refuses to boot without an
        # env-provided key whenever DEBUG is off (i.e. production).
        SECRET_KEY = "django-insecure-dev-only-key-change-me-in-production"  # nosec B105
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY environment variable must be set when DEBUG is "
            "off. Generate one with: "
            "python -c \"import secrets; print(secrets.token_urlsafe(50))\""
        )

# Comma-separated list, e.g. "localhost,127.0.0.1,timeline.example.com"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django.contrib.sites is required by allauth.
    "django.contrib.sites",
    # Third-party
    "rest_framework",
    # authtoken backs dj-rest-auth's TokenModel imports (we use JWT, but the
    # library still references it — cheap to include, avoids import surprises).
    "rest_framework.authtoken",
    "corsheaders",
    # Auth stack: dj-rest-auth exposes the API endpoints; allauth powers
    # registration + email-based login. See docs/reference/accounts.md.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # Stores refresh tokens that have been rotated away or explicitly logged out
    # (Phase 9). Required by SIMPLE_JWT's BLACKLIST_AFTER_ROTATION below —
    # without it, an "old" refresh token would keep working after rotation.
    "rest_framework_simplejwt.token_blacklist",
    # Local apps
    "accounts",
    "api",
]

# django.contrib.sites — single site; required by allauth.
SITE_ID = 1

# Our custom user model (email login, no username). MUST be set before the
# first migration that creates the user table (see docs/reference/accounts.md).
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves collected static files (admin + DRF browsable API) in
    # production; it must sit directly after SecurityMiddleware. Harmless in dev
    # (Django's staticfiles app still serves them there via runserver).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # CORS must come before CommonMiddleware so it can add headers to responses.
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Required by allauth (>=0.55): populates request for the account flows.
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "timeline"),
        "USER": os.environ.get("POSTGRES_USER", "timeline"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "timeline"),
        # "db" is the postgres service name in docker-compose.yml.
        "HOST": os.environ.get("POSTGRES_HOST", "db"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` gathers Django's own static files (admin, DRF browsable
# API) in production so WhiteNoise can serve them. Unused by the dev runserver,
# which serves them straight from each app — so this is harmless in dev.
STATIC_ROOT = BASE_DIR / "staticfiles"

# User-uploaded files (post photos, avatars — Phase 4).
# In development these live in a local folder (bind-mounted / gitignored) and are
# served by Django (see config/urls.py, DEBUG-only). Production will move them to
# private object storage with auth-gated/signed URLs — see Phase 7. Filenames get
# a UUID (see api/imaging.py) so a raw media URL can't be guessed by walking ids.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Where media files actually live, chosen by config so the backend can be
# swapped without touching model/view code (django-storages). Local disk now —
# and through the Phase 7 home-server beta — flipping to an S3 bucket at the AWS
# migration (Phase 7b) by setting DJANGO_MEDIA_STORAGE=s3 and the bucket env
# vars below (which pulls in django-storages' S3 backend + boto3 at that point).
if os.environ.get("DJANGO_MEDIA_STORAGE") == "s3":
    _default_storage = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ.get("AWS_STORAGE_BUCKET_NAME", ""),
            "region_name": os.environ.get("AWS_S3_REGION_NAME", ""),
            # Private by default: objects aren't world-readable; the app serves
            # them via signed URLs. Keeps real friends'/family's photos private.
            "default_acl": "private",
            "querystring_auth": True,
        },
    }
else:
    _default_storage = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        # Dev: plain storage (runserver serves straight from the apps). Prod:
        # WhiteNoise's compressed, hash-manifested storage — long-cache-friendly
        # filenames + gzip/brotli, built by `collectstatic`.
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Caching
# DRF's request throttling (see DEFAULT_THROTTLE_RATES below) keeps its per-IP /
# per-user counters in Django's cache. In production the app runs under several
# gunicorn worker processes, so the cache MUST be shared across them — a
# per-process in-memory cache would give each worker its own counter and the
# real limit would balloon to (rate x workers). The boring, no-new-infrastructure
# choice on a single box is Django's database cache: it reuses the Postgres we
# already run, is shared by every worker, and survives restarts. The cache table
# is created by `manage.py createcachetable` (run in entrypoint.prod.sh, and
# automatically during the test-database setup). Dev runs a single-process
# runserver, so a local in-memory cache is fine there and saves creating a table.
if DEBUG:
    CACHES = {
        "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "timeline_cache",
        }
    }

# Django REST Framework
# Phase 2: default every endpoint to "must be logged in", authenticated via the
# JWT that lives in an httpOnly cookie. Endpoints that must stay open (login,
# register, the CSRF primer, the Phase 0 smoke test) opt out with AllowAny.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Feed and post lists are paginated so a long history doesn't ship in one
    # response. Clients follow the `next` URL to load more. 20 is a comfortable
    # page for a text feed; revisit if it feels short in real use.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Exactly ONE trusted proxy sits in front of us in production: Caddy (see
    # deploy/Caddyfile), which appends the real client IP to X-Forwarded-For.
    # Telling DRF NUM_PROXIES=1 makes it take the LAST address in that header —
    # the one Caddy added — as the throttle identity. WITHOUT this, DRF falls
    # back to using the *entire* X-Forwarded-For string; since Caddy appends to
    # (rather than replaces) any client-supplied header, an attacker could send a
    # rotating `X-Forwarded-For: <junk>` prefix and get a fresh throttle bucket
    # per request, bypassing the per-IP login limit entirely. This is the crux
    # that makes the login throttle below actually hold. (Only /api/* rides this
    # proxy; the admin LAN restriction uses Caddy's own remote_ip, not this.)
    "NUM_PROXIES": 1,
    # Rate limits for the auth-sensitive endpoints (see the throttled views in
    # accounts/views.py and DeleteAccountView). We deliberately DON'T set
    # DEFAULT_THROTTLE_CLASSES — throttling is opt-in per view via a scope, so
    # only these named scopes are limited; the rest of the API is untouched.
    #   - login: per-IP (the caller is anonymous), to blunt online password
    #     guessing against known accounts. Keyed on IP rather than the submitted
    #     email on purpose: an email-keyed limit would let an attacker lock a
    #     victim out of their own login by burning their bucket (a DoS).
    #   - password_change / account_delete: per-user (the caller is logged in),
    #     to blunt guessing the *current* password from a hijacked session.
    # A tripped limit returns a clean 429 with a `detail` message the SPA already
    # surfaces. Override via env if a real family member ever hits a wall.
    "DEFAULT_THROTTLE_RATES": {
        "login": os.environ.get("DJANGO_THROTTLE_LOGIN", "10/min"),
        "password_change": os.environ.get(
            "DJANGO_THROTTLE_PASSWORD_CHANGE", "10/min"
        ),
        "account_delete": os.environ.get(
            "DJANGO_THROTTLE_ACCOUNT_DELETE", "5/min"
        ),
        # register a device for push (per-user; the caller is logged in). The
        # app registers once per launch, so a real client never approaches this;
        # it caps how fast one account can accumulate DevicePushToken rows by
        # POSTing distinct fabricated token values.
        "push_register": os.environ.get("DJANGO_THROTTLE_PUSH_REGISTER", "20/min"),
        # resend a verification code (per-IP; the caller is anonymous). Blunts
        # using the resend endpoint to spam an inbox / probe. A per-email cooldown
        # (EmailVerificationCode.RESEND_COOLDOWN) guards a single address on top.
        "resend_verification": os.environ.get(
            "DJANGO_THROTTLE_RESEND_VERIFICATION", "5/min"
        ),
        # redeem a verification code (per-IP). The per-code 5-attempt budget only
        # guards a single known code; this stops an attacker hammering the endpoint
        # across many emails. Generous so a fat-fingered real user isn't blocked.
        "verify_email": os.environ.get("DJANGO_THROTTLE_VERIFY_EMAIL", "20/min"),
        # request a forgotten-password reset (per-IP; caller is anonymous). Same
        # role as resend_verification: blunts inbox-spamming / probing via the
        # reset-request endpoint. A per-email cooldown (PasswordResetCode.
        # RESEND_COOLDOWN) guards a single address on top.
        "password_reset": os.environ.get("DJANGO_THROTTLE_PASSWORD_RESET", "5/min"),
        # confirm a reset code + set a new password (per-IP). This is the
        # account-takeover surface; the per-code 5-attempt budget only guards one
        # known code, so this caps hammering across many emails. Generous so a real
        # user retrying a weak password isn't blocked.
        "password_reset_confirm": os.environ.get(
            "DJANGO_THROTTLE_PASSWORD_RESET_CONFIRM", "20/min"
        ),
    },
}

# --- Authentication (dj-rest-auth + allauth + simplejwt) ---------------------
# JWT delivered in an httpOnly cookie so page JavaScript can't read it: an XSS
# bug then can't exfiltrate a login. See docs/reference/accounts.md.
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "timeline-auth",
    "JWT_AUTH_REFRESH_COOKIE": "timeline-refresh",
    # httpOnly: not readable by JavaScript (XSS mitigation).
    "JWT_AUTH_HTTPONLY": True,
    # Lax lets the cookie ride same-site navigations but not cross-site POSTs —
    # a first line of CSRF defence. Secure is added in production (Phase 7).
    "JWT_AUTH_SAMESITE": "Lax",
    "JWT_AUTH_SECURE": env_bool("DJANGO_COOKIE_SECURE", default=not DEBUG),
    # With the token in a cookie, require a CSRF token on unsafe (mutating)
    # requests — belt-and-braces alongside SameSite.
    "JWT_AUTH_COOKIE_USE_CSRF": True,
    # We authenticate with JWT only; don't also open a Django session on login.
    "SESSION_LOGIN": False,
    "REGISTER_SERIALIZER": "accounts.serializers.CustomRegisterSerializer",
    "USER_DETAILS_SERIALIZER": "accounts.serializers.UserDetailsSerializer",
    # Login also requires a verified email (issue #73), on top of correct
    # credentials + admin approval. See accounts.serializers.CustomLoginSerializer.
    "LOGIN_SERIALIZER": "accounts.serializers.CustomLoginSerializer",
    # Require the current password to change it (dj-rest-auth leaves this off by
    # default). Account hygiene: a hijacked session (e.g. via XSS) then can't
    # silently rotate the password without also knowing the old one, and it stops
    # a shoulder-surfer at an unlocked screen from locking the owner out.
    "OLD_PASSWORD_FIELD_ENABLED": True,  # nosec B105 — a feature flag, not a password
}

SIMPLE_JWT = {
    # Longer-lived access token: the *web* frontend doesn't do silent refresh, so
    # a short access lifetime would log family members out constantly. Phase 9's
    # mobile client DOES refresh silently, but this setting is shared by both —
    # deliberately left at a day so shortening it for the app can't quietly start
    # logging people out of the website. Revisit only alongside web refresh.
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    # This is the *web* refresh lifetime, and it also sets the max-age of the
    # `timeline-refresh` cookie dj-rest-auth hands browsers. Kept short (1 day,
    # matching the access token) because the website has no silent refresh, so a
    # longer-lived refresh cookie would be extra exposure on a shared or borrowed
    # machine for no benefit. The native app's much longer lifetime lives in
    # MOBILE_REFRESH_TOKEN_LIFETIME below, NOT here — see accounts/tokens.py.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Every refresh returns a NEW refresh token and blacklists the old one.
    # Without rotation, one captured refresh token would be a 90-day skeleton key.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# The native app's refresh lifetime — deliberately NOT inside SIMPLE_JWT, because
# that dict is global and the web must stay short (see REFRESH_TOKEN_LIFETIME
# above). `accounts.tokens.MobileRefreshToken` reads this; only tokens carrying
# the `client: "mobile"` claim can ever be rotated at this lifetime, so a stolen
# browser cookie can't be upgraded into a 90-day one.
#
# 90 days is defensible only because rotation is on: each refresh invalidates the
# token that bought it, so a stolen mobile token is useful until its owner next
# opens the app, not for three months.
MOBILE_REFRESH_TOKEN_LIFETIME = timedelta(
    days=env_int("DJANGO_MOBILE_REFRESH_DAYS", default=90)
)

# allauth: email is the login identifier; there is no username field.
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
# We run our own 6-digit-code email verification (issue #73) rather than
# allauth's built-in link flow, so allauth's own verification stays off here.
# allauth still creates an EmailAddress row at sign-up; our flow flips its
# `verified` flag (the source of truth the login check reads), and admin approval
# (is_active) remains the separate membership gate. See docs/reference/accounts.md.
ACCOUNT_EMAIL_VERIFICATION = "none"

# allauth needs an authentication backend alongside Django's default.
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# --- Email -------------------------------------------------------------------
# In production we send over SMTP; any transactional provider works (we use
# Resend), configured entirely through env so switching providers is only a
# credentials change. Provider + SPF/DKIM setup is documented in docs/deploy.md.
#
# Backend selection is presence-based: EMAIL_HOST set ⇒ SMTP. With no host we
# fall back to the console backend (mail printed to the logs) — but *only* when
# that's explicitly allowed, which defaults to on in DEBUG and off otherwise.
# The console backend prints reset/verification links in full, i.e. a plaintext
# account-takeover token; in production an accidentally-unset EMAIL_HOST must
# fail the deploy, not silently start logging those tokens. A deliberate LAN
# test (DEBUG off, no provider yet) opts back in with EMAIL_CONSOLE_FALLBACK=true.
EMAIL_CONSOLE_FALLBACK = env_bool("EMAIL_CONSOLE_FALLBACK", default=DEBUG)


def _email_backend(host, console_fallback):
    if host:
        return "django.core.mail.backends.smtp.EmailBackend"
    if console_fallback:
        return "django.core.mail.backends.console.EmailBackend"
    raise ImproperlyConfigured(
        "No email backend configured: set EMAIL_HOST (see docs/deploy.md → "
        "Outbound email), or set EMAIL_CONSOLE_FALLBACK=true to print mail to "
        "the logs instead. The console fallback is off by default in production "
        "because password-reset links would be written to the logs in plaintext."
    )


EMAIL_BACKEND = _email_backend(os.environ.get("EMAIL_HOST"), EMAIL_CONSOLE_FALLBACK)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
# STARTTLS on the submission port (587) is the common default. For a provider
# that wants implicit TLS on 465 instead, set EMAIL_USE_TLS=false,
# EMAIL_USE_SSL=true, EMAIL_PORT=465. (The two must not both be true.)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=False)
# Cap how long a single send may block. Without it, the SMTP call can hang on a
# slow or unreachable provider and tie up the worker (a stuck password-reset
# request) until gunicorn's worker-timeout kills it. Seconds.
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 10)
# The From address on outbound mail. It must live on a domain verified with the
# provider (SPF/DKIM) or the mail is spam-filtered/dropped — see docs/deploy.md.
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "TimeLine <no-reply@your-timeline.net>"
)
# Address for Django's own error mail (distinct from user-facing mail); align it.
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# CORS — which browser origins may call this API.
# The React dev server (Vite) runs on :5173. Comma-separated list via env.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if o.strip()
]
# The SPA sends the auth + CSRF cookies with its fetches (credentials:include),
# so the browser needs an explicit credentials-allowed CORS response. Never
# combine this with a wildcard origin.
CORS_ALLOW_CREDENTIALS = True

# Cross-origin (Vite :5173 → Django :8000) unsafe requests must have their
# Origin trusted for Django's CSRF check. Same allowlist as CORS. In the
# same-origin production setup (Caddy serves SPA + API on one domain), this is
# set to https://your-timeline.net via DJANGO_CORS_ALLOWED_ORIGINS.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)


# --- Production security -------------------------------------------------------
# Everything below only bites with DEBUG off (the home-server/prod deploy) — dev
# stays plain HTTP. Behind Caddy, which terminates TLS and forwards the original
# scheme in this header, so Django's request.is_secure() reports HTTPS correctly.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Send the session + CSRF cookies only over HTTPS in production. Mirrors the JWT
# cookie's DJANGO_COOKIE_SECURE (defaults to "on unless DEBUG"). The CSRF cookie
# deliberately stays readable by JS (not httpOnly) so the SPA can echo it back in
# the X-CSRFToken header — see the CSRF note in docs/reference/accounts.md.
SESSION_COOKIE_SECURE = env_bool("DJANGO_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_COOKIE_SECURE", default=not DEBUG)

# HSTS tells browsers "only ever reach this domain over HTTPS". Opt-in via env,
# default OFF: during the beta a certificate hiccup shouldn't hard-lock the domain
# to HTTPS in visitors' browsers. Once stable, raise DJANGO_HSTS_SECONDS to e.g.
# 2592000 (30 days), then 31536000 (1 year), before considering preload.
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_HSTS_INCLUDE_SUBDOMAINS", default=False
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_HSTS_PRELOAD", default=False)
