"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    """Read a boolean-ish environment variable ("1"/"true"/"yes")."""
    return os.environ.get(name, str(default)).lower() in {"1", "true", "yes"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Secure by default: DEBUG is off unless explicitly enabled. The dev
# docker-compose sets DJANGO_DEBUG=true, so local development is unaffected.
DEBUG = env_bool("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# In development we fall back to a throwaway key. With DEBUG off (i.e. anything
# that looks like production) the key MUST come from the environment — we refuse
# to boot with a repo-visible key, since a public SECRET_KEY lets anyone forge
# session cookies and signed tokens (password resets, etc.).
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        # Dev-only fallback; the `else` branch above refuses to boot without an
        # env-provided key whenever DEBUG is off (i.e. production).
        SECRET_KEY = "django-insecure-dev-only-key-change-me-in-production"  # nosec B105
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY environment variable must be set when DEBUG is "
            "off. Generate one with: "
            "python -c \"import secrets; print(secrets.token_urlsafe(50))\""
        )

# Comma-separated list, e.g. "localhost,127.0.0.1,timeline.example.com"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django.contrib.sites is required by allauth.
    "django.contrib.sites",
    # Third-party
    "rest_framework",
    # authtoken backs dj-rest-auth's TokenModel imports (we use JWT, but the
    # library still references it — cheap to include, avoids import surprises).
    "rest_framework.authtoken",
    "corsheaders",
    # Auth stack: dj-rest-auth exposes the API endpoints; allauth powers
    # registration + email-based login. See docs/phases/phase-2-accounts.md.
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # Local apps
    "accounts",
    "api",
]

# django.contrib.sites — single site; required by allauth.
SITE_ID = 1

# Our custom user model (email login, no username). MUST be set before the
# first migration that creates the user table (see phase-2 notes / DB reset).
AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CORS must come before CommonMiddleware so it can add headers to responses.
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Required by allauth (>=0.55): populates request for the account flows.
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "timeline"),
        "USER": os.environ.get("POSTGRES_USER", "timeline"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "timeline"),
        # "db" is the postgres service name in docker-compose.yml.
        "HOST": os.environ.get("POSTGRES_HOST", "db"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# User-uploaded files (post photos, avatars — Phase 4).
# In development these live in a local folder (bind-mounted / gitignored) and are
# served by Django (see config/urls.py, DEBUG-only). Production will move them to
# private object storage with auth-gated/signed URLs — see Phase 7. Filenames get
# a UUID (see api/imaging.py) so a raw media URL can't be guessed by walking ids.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Where media files actually live, chosen by config so the backend can be
# swapped without touching model/view code (django-storages). Local disk now —
# and through the Phase 7 home-server beta — flipping to an S3 bucket at the AWS
# migration (Phase 7b) by setting DJANGO_MEDIA_STORAGE=s3 and the bucket env
# vars below (which pulls in django-storages' S3 backend + boto3 at that point).
if os.environ.get("DJANGO_MEDIA_STORAGE") == "s3":
    _default_storage = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ.get("AWS_STORAGE_BUCKET_NAME", ""),
            "region_name": os.environ.get("AWS_S3_REGION_NAME", ""),
            # Private by default: objects aren't world-readable; the app serves
            # them via signed URLs. Keeps real friends'/family's photos private.
            "default_acl": "private",
            "querystring_auth": True,
        },
    }
else:
    _default_storage = {"BACKEND": "django.core.files.storage.FileSystemStorage"}

STORAGES = {
    "default": _default_storage,
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django REST Framework
# Phase 2: default every endpoint to "must be logged in", authenticated via the
# JWT that lives in an httpOnly cookie. Endpoints that must stay open (login,
# register, the CSRF primer, the Phase 0 smoke test) opt out with AllowAny.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Feed and post lists are paginated so a long history doesn't ship in one
    # response. Clients follow the `next` URL to load more. 20 is a comfortable
    # page for a text feed; revisit if it feels short in real use.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# --- Authentication (dj-rest-auth + allauth + simplejwt) ---------------------
# JWT delivered in an httpOnly cookie so page JavaScript can't read it: an XSS
# bug then can't exfiltrate a login. See docs/phases/phase-2-accounts.md.
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "timeline-auth",
    "JWT_AUTH_REFRESH_COOKIE": "timeline-refresh",
    # httpOnly: not readable by JavaScript (XSS mitigation).
    "JWT_AUTH_HTTPONLY": True,
    # Lax lets the cookie ride same-site navigations but not cross-site POSTs —
    # a first line of CSRF defence. Secure is added in production (Phase 7).
    "JWT_AUTH_SAMESITE": "Lax",
    "JWT_AUTH_SECURE": env_bool("DJANGO_COOKIE_SECURE", default=not DEBUG),
    # With the token in a cookie, require a CSRF token on unsafe (mutating)
    # requests — belt-and-braces alongside SameSite.
    "JWT_AUTH_COOKIE_USE_CSRF": True,
    # We authenticate with JWT only; don't also open a Django session on login.
    "SESSION_LOGIN": False,
    "REGISTER_SERIALIZER": "accounts.serializers.CustomRegisterSerializer",
    "USER_DETAILS_SERIALIZER": "accounts.serializers.UserDetailsSerializer",
}

SIMPLE_JWT = {
    # Longer-lived access token: the frontend doesn't do silent refresh yet, so
    # a short access lifetime would log family members out constantly. Revisit
    # (add refresh-on-401) if/when that matters.
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# allauth: email is the login identifier; there is no username field.
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
# Gating is admin approval (is_active), not email verification — so no email
# sending is wired up in this phase.
ACCOUNT_EMAIL_VERIFICATION = "none"

# allauth needs an authentication backend alongside Django's default.
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# CORS — which browser origins may call this API.
# The React dev server (Vite) runs on :5173. Comma-separated list via env.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if o.strip()
]
# The SPA sends the auth + CSRF cookies with its fetches (credentials:include),
# so the browser needs an explicit credentials-allowed CORS response. Never
# combine this with a wildcard origin.
CORS_ALLOW_CREDENTIALS = True

# Cross-origin (Vite :5173 → Django :8000) unsafe requests must have their
# Origin trusted for Django's CSRF check. Same allowlist as CORS.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)
