// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // `.expo` is generated by the router at build time and isn't committed —
    // linting it only ever reports on code we didn't write and can't fix.
    ignores: ["dist/*", ".expo/*"],
  },
  {
    // Jest's globals, for the plain-JS setup file. The TypeScript suites don't
    // need this — `no-undef` is off for TS, where the compiler answers the same
    // question properly — but `jest.setup.js` is linted as ordinary JS and every
    // `jest.mock` in it read as an undefined variable. Declared by hand rather
    // than pulling in the `globals` package for two names.
    files: ["jest.setup.js"],
    languageOptions: {
      globals: {
        jest: "readonly",
        beforeEach: "readonly",
      },
    },
  },
]);
